### ISSUE TITLE
d3v5 : error TS2345: Argument of type 'Selection<BaseType, { date: Date; score: number; }, SVGGElement, unknown>' is not assignable to parameter of type 'Selection<SVGGElement, { date: Date; score: number; }, SVGGElement, unknown>'

### ISSUE THREAD

**Issue by Abdelkrim** [Ledragon/d3v4-ts-demo#2]
Hi @Ledragon,
any idea how I can get rid of this error while using d3v5?

Thank you for your help

> src/app.ts:85:30 - 
> 
>     error TS2345: Argument of type 'Selection<BaseType, { date: Date; score: number; }, SVGGElement, unknown>' is not assignable to parameter of type 'Selection<SVGGElement, { date: Date; score: number; }, SVGGElement, unknown>'.
> 
>     Type 'BaseType' is not assignable to type 'SVGGElement'.
> 
>     Type 'null' is not assignable to type 'SVGGElement'.
> 

```javascript
Line 85   enterSelection.merge(dataBound)
```

```json

{
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": false,
        "declaration": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "es2015",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "outDir": "./dist/js",
        "sourceMap": true,
        "strictNullChecks": true,
        "target": "es5"
    },
    "files": [
        "src/app.ts",
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```

**Comment by Ledragon** [comment]
Hi,
I think you should have the type `SVGGElement|null` instead of just `SVGGElement`, but it's kinda hard to tell without seeing the whole code

**Comment by ashvaibhav** [comment]
My code:

`
    var bars = svg.selectAll("g.layer").selectAll("rect")
      .data((d:any) => d, (e:any) => e.data.state);

    bars.exit().remove()

    bars.enter().append("rect")
      .attr("width", x.bandwidth())
      .merge(bars) // Line 110

`

My error:
`

src/components/Charts/Bar/Bar.tsx:110:14 - error TS2345: Argument of type 'Selection<BaseType, unknown, BaseType, unknown>' is not assignable to parameter of type 'Selection<SVGRectElement, unknown, BaseType, unknown>'.
      Types of property 'select' are incompatible.
        Type '{ <DescElement extends d3.BaseType>(selector: string): d3.Selection<DescElement, unknown, d3.BaseType, unknown>; <DescElement extends d3.BaseType>(selector: null): d3.Selection<null, undefined, d3.BaseType, unknown>; <DescElement extends d3.BaseType>(selector: d3.ValueFn<...>): d3.Selection<...>; }' is not assignable to type '{ <DescElement extends d3.BaseType>(selector: string): d3.Selection<DescElement, unknown, d3.BaseType, unknown>; <DescElement extends d3.BaseType>(selector: null): d3.Selection<null, undefined, d3.BaseType, unknown>; <DescElement extends d3.BaseType>(selector: d3.ValueFn<...>): d3.Selection<...>; }'. Two different types with this name exist, but they are unrelated.
          Types of parameters 'selector' and 'selector' are incompatible.
            Types of parameters 'groups' and 'groups' are incompatible.
              Type 'BaseType[] | ArrayLike<BaseType>' is not assignable to type 'SVGRectElement[] | ArrayLike<SVGRectElement>'.
                Type 'BaseType[]' is not assignable to type 'SVGRectElement[] | ArrayLike<SVGRectElement>'.
                  Type 'BaseType[]' is not assignable to type 'SVGRectElement[]'.
                    Type 'BaseType' is not assignable to type 'SVGRectElement'.
                      Type 'null' is not assignable to type 'SVGRectElement'.

    110       .merge(bars)
                     ~~~~

`

**Comment by Ledragon** [comment]
It looks like you're merging with unbound data

**Comment by Abdelkrim** [comment]
@Ledragon @ashvaibhav thank you for the feedback; I'll close the issue while investigating. I guess that I screwed that part of the code eventually
